services:
  ollama_service:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama-volume:/root/.ollama
    #   spring boot will pull the model automatically, uncomment below if required to pull other model or running standalone
    # - ./entrypoint.sh:/entrypoint.sh
    pull_policy: missing
    tty: true
    restart: unless-stopped
    #   spring boot will pull the model automatically, uncomment below if required to pull other model or running standalone
    #entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui_container
    environment:
      - OLLAMA_BASE_URL=http://ollama_service:11434
      - WEBUI_AUTH= false
    depends_on:
      - ollama_service
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-volume:/app/backend/data
    restart: unless-stopped

  # Redis Standalone Built-in insight UI http://localhost:8001
  redis_service:
    image: redis/redis-stack:latest
    container_name: redislabs_container
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_volume:/data
    networks:
      - ollama_networks

volumes:
  open-webui-volume: { }
  ollama-volume: { }
  redisinsight_db: