services:
  ollama-model:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    pull_policy: missing
    tty: true
    restart: no
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports:
      - '3000:3000'