global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: SpringAi-observability

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: 'Spring-Boot'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]