server.port=${SERVER_PORT:8082}
spring.ai.mcp.server.name=${MCP_SERVER_NAME:buyer-service}
spring.ai.mcp.server.version=${MCP_SERVER_VERSION:1.0.1}
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.sse-endpoint=${MCP_SERVER_SSE_ENDPOINT:/sse}
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:llama3.1:latest}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
