spring.application.name=SpringAi
spring.docker.compose.lifecycle-management=start_only
spring.threads.virtual.enabled=true
# The default Ollama Model in Spring Ai is mistral, but it can be changed by setting the below property. make sure to download the same model in entrypoint.sh file
spring.ai.ollama.chat.options.model=llama3.1:latest
# If running the Ollama Docker Instance separately, then set this property to false
spring.docker.compose.enabled=true
spring.docker.compose.start.log-level=debug
# Database Configuration (Example with H2)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:jdbcChatMemory
spring.h2.console.path=/h2-console
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Spring AI JDBC memory schema initialization
spring.ai.chat.memory.repository.jdbc.initialize-schema=always