server.port=8083
spring.ai.mcp.server.name=seller-service
spring.ai.mcp.server.version=1.0.1
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.ollama.chat.model=llama3.1:latest



