services:
  ollama_service:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - "11434:11434"
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama_volume:/root/.ollama
    #   spring boot will pull the model automatically, uncomment below if required to pull other model or running standalone
    # - ./entrypoint.sh:/entrypoint.sh
    pull_policy: missing
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_NUM_PARALLEL=1
    #   spring boot will pull the model automatically, uncomment below if required to pull other model or running standalone
    #entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    networks:
      - ollama_networks

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui_container
    environment:
      - OLLAMA_BASE_URL=http://ollama_service:11434
      - WEBUI_AUTH= false
    depends_on:
      - ollama_service
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open_webui_volume:/app/backend/data
    restart: unless-stopped
    networks:
      - ollama_networks

volumes:
  open_webui_volume: { }
  ollama_volume: { }
networks:
  ollama_networks:
    driver: bridge