services:
  ollama-model:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama-volume:/root/.ollama
    pull_policy: missing
    tty: true
    restart: unless-stopped
    # entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui_container
    environment:
      WEBUI_AUTH: false
    depends_on:
      - ollama-model
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-volume:/app/backend/data
    restart: unless-stopped

  redis:
    image: redislabs/redismod
    container_name: redislabs_container
    restart: unless-stopped
    ports:
      - "6379:6379"

  #  in redis-insight ui, add host name as redis
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight_container
    restart: unless-stopped
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_db:/db

volumes:
  open-webui-volume: { }
  ollama-volume: { }
  redisinsight_db: